[tool.black]
line-length = 120

[tool.poetry]
name = "library-registry"
version = "0.0.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "CC0-1.0"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
invoke = "^1.5.0"
black = "^21.11b1"
flake8 = "^4.0.1"
pep8-naming = "^0.12.1"
yamllint = "^1.26.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
