[tool.poetry]
name = "library-manager-list"
version = "0.0.0"
description = "Arduino Library Manager list"
authors = ["Arduino <info@arduino.cc>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
codespell = ">=2.0.0"
