# Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-yaml-task.md
name: Check YAML

env:
  # See: https://github.com/actions/setup-python/tree/v2#available-versions-of-python
  PYTHON_VERSION: "3.9"

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".yamllint*"
      - "poetry.lock"
      - "pyproject.toml"
      # Source: https://github.com/ikatyang/linguist-languages/blob/master/data/YAML.json (used by Prettier)
      - "**/.clang-format"
      - "**/.clang-tidy"
      - "**/.gemrc"
      - "**/glide.lock"
      - "**.ya?ml*"
      - "**.mir"
      - "**.reek"
      - "**.rviz"
      - "**.sublime-syntax"
      - "**.syntax"
  pull_request:
    paths:
      - ".yamllint*"
      - "poetry.lock"
      - "pyproject.toml"
      # Source: https://github.com/ikatyang/linguist-languages/blob/master/data/YAML.json (used by Prettier)
      - "**/.clang-format"
      - "**/.clang-tidy"
      - "**/.gemrc"
      - "**/glide.lock"
      - "**.ya?ml*"
      - "**.mir"
      - "**.reek"
      - "**.rviz"
      - "**.sublime-syntax"
      - "**.syntax"
  workflow_dispatch:
  repository_dispatch:

jobs:
  check:
    name: ${{ matrix.configuration.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        configuration:
          - name: Generate problem matcher output
            # yamllint's "github" output type produces annotated diffs, but is not useful to humans reading the log.
            format: github
            # The other matrix job is used to set the result, so this job is configured to always pass.
            continue-on-error: true
          - name: Check formatting
            # yamllint's "colored" output type is most suitable for humans reading the log.
            format: colored
            continue-on-error: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        run: pip install poetry

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Check YAML
        continue-on-error: ${{ matrix.configuration.continue-on-error }}
        run: task yaml:lint YAMLLINT_FORMAT=${{ matrix.configuration.format }}
