name: Check license

on:
  push:
    paths:
      - ".github/workflows/check-license.yml"
      - "Taskfile.yml"
      # Recognized license files. See: https://github.com/licensee/licensee/blob/master/docs/what-we-look-at.md#detecting-the-license-file
      - "COPYING*"
      - "LICENCE*"
      - "LICENSE*"
  pull_request:
    paths:
      - ".github/workflows/check-license.yml"
      - "Taskfile.yml"
      # Recognized license files. See: https://github.com/licensee/licensee/blob/master/docs/what-we-look-at.md#detecting-the-license-file
      - "COPYING*"
      - "LICENCE*"
      - "LICENSE*"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout local repository
        uses: actions/checkout@v2

      - name: Install Taskfile
        uses: arduino/actions/setup-taskfile@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby # Install latest version

      - name: Install licensee
        run: gem install licensee

      # See: https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository
      - name: Check license file
        run: task --silent docs:check-license
